Feature/fix bot schemas
Sonia-corporation/hellforge pull request #14
Opened 2020-08-29 14:51 UTC by asmodee-bellanie

Fixes the schemas importations.
- Fixes few linter issues.

2020-08-29 21:13 UTC, C0ZEN commented on src/services/app-ready/app-ready.service.ts
> +    void MongooseConnectService.getInstance().init();
You can return a Promise here

2020-08-29 21:14 UTC, C0ZEN requested changes
A small comment ;)

2020-08-29 22:52 UTC, asmodee-bellanie commented on src/services/app-ready/app-ready.service.ts
> +    void MongooseConnectService.getInstance().init();
How? ^^

2020-08-30 07:59 UTC, C0ZEN approved these changes

2020-08-30 08:00 UTC, merged