Feature/base code
Sonia-corporation/hellforge pull request #2
Opened 2020-08-22 13:46 UTC by asmodee-bellanie

Starts the first code bits for the minimum functionnality.

2020-08-22 22:21 UTC, C0ZEN requested changes
Add comments

2020-08-22 22:21 UTC, C0ZEN commented on package.json
> +    "start": "concurrently \"tsc --watch\" \"nodemon ./dist/src/features/hellforge.js\"",
Well maybe this is like this because this is the initial configuration but the path of the dist should be simple. just dist/something.js

2020-08-22 22:21 UTC, C0ZEN commented on src/features/hellforge.spec.ts
> +import { Hellforge } from "./hellforge"
Woooow calm down. is this a fucking coverage?

2020-08-22 22:21 UTC, C0ZEN commented on tsconfig.json
> +        "cacheBetweenTests": false
is this a configuration from my project?
if yes I think that we should both try to enable this

2020-08-22 22:21 UTC, C0ZEN commented on src/features/hellforge.ts
> +    this._client.on('ready', () => {
I think that this service should defer the logic from the point where you start calling discord stuff.
so the listener ready and everything related to it should be already in a dedicated service like discord service or discord ready service

2020-08-23 11:11 UTC, asmodee-bellanie commented on package.json
> +    "start": "concurrently \"tsc --watch\" \"nodemon ./dist/src/features/hellforge.js\"",
Ok

2020-08-23 11:11 UTC, asmodee-bellanie commented on src/features/hellforge.spec.ts
> +import { Hellforge } from "./hellforge"
Nope! xD

I tried to do it, but I couldn't. So It's not a coverage really... xD

2020-08-23 11:12 UTC, asmodee-bellanie commented on tsconfig.json
> +        "cacheBetweenTests": false
I may have forgotten to remove that. But yes, it would be nice to.

2020-08-23 11:12 UTC, asmodee-bellanie commented on src/features/hellforge.ts
> +    this._client.on('ready', () => {
In fact done in the next PR.

2020-08-23 13:31 UTC, C0ZEN commented on package.json
> +    "start": "concurrently \"tsc --watch\" \"nodemon ./dist/src/features/hellforge.js\"",
@asmodee-bellanie so, the path was not good or just the build?

2020-08-23 13:34 UTC, C0ZEN commented on src/features/hellforge.ts
> +    this._client.on('ready', () => {
cool

2020-08-23 13:35 UTC, C0ZEN approved these changes

2020-08-23 13:35 UTC, merged